server:
  port: 8081

hibiscus:
  helper:
    scan-path: com.hibiscus.docs.core
  
  # 页面访问控制配置
  security:
    # 是否启用页面访问控制
    enabled: true
    # 允许访问的IP地址（支持CIDR格式）
    allowed-ips:
      - "127.0.0.1"
      - "::1"
      - "192.168.0.0/16"
      - "10.0.0.0/8"
    # 是否允许本地访问
    allow-localhost: true
    # 访问控制模式：ip, token, both
    mode: "both"
    # 访问令牌（用于API访问）
    access-token: "hibiscus-api-2024"
    # 令牌过期时间（小时）
    token-expire-hours: 24
  
  # 高级功能配置
  advanced:
    # 是否启用请求日志记录
    enable-request-logging: true
    # 是否启用性能监控
    enable-performance-monitoring: true
    # 是否启用API限流
    enable-rate-limiting: true
    # 限流配置
    rate-limit:
      requests-per-minute: 100
      burst-capacity: 20
    # 缓存配置
    cache:
      enabled: true
      ttl-seconds: 300
      max-size: 1000
  
  # 接口测试配置
  testing:
    # 默认请求头
    default-headers:
      "User-Agent": "Hibiscus-API-Tester/1.0"
      "Accept": "application/json"
    # 超时配置（毫秒）
    timeout:
      connect: 5000
      read: 30000
    # 是否允许跨域测试
    allow-cors-testing: true
    # 测试环境配置
    environments:
      local:
        base-url: "http://localhost:8081"
        description: "本地开发环境"
      dev:
        base-url: "https://dev-api.example.com"
        description: "开发环境"
      prod:
        base-url: "https://api.example.com"
        description: "生产环境"

# 告警系统配置
alerts:
  # 内存告警阈值
  memory:
    warning-threshold: 80.0    # 警告阈值：80%
    critical-threshold: 90.0   # 严重阈值：90%
  
  # 系统负载告警阈值
  system-load:
    warning-threshold: 0.8     # 警告阈值：0.8
    critical-threshold: 0.9    # 严重阈值：0.9
  
  # 响应时间告警阈值（毫秒）
  response-time:
    warning-threshold: 5000    # 警告阈值：5秒
    critical-threshold: 10000  # 严重阈值：10秒
  
  # 线程数告警阈值
  thread-count:
    warning-threshold: 200     # 警告阈值：200
    critical-threshold: 300    # 严重阈值：300
  
  # 告警冷却时间（毫秒）
  cooldown:
    warning: 300000            # 警告告警：5分钟
    critical: 30000            # 严重告警：30秒
  
  # 告警通知配置
  notifications:
    enabled: true
    email:
      enabled: false
      smtp-server: "smtp.example.com"
      smtp-port: 587
      username: "alerts@example.com"
      password: ""
    webhook:
      enabled: false
      url: "https://webhook.example.com/alerts"
      timeout: 5000
    log-file:
      enabled: true
      path: "logs/alerts.log"
      max-size: "100MB"
      max-files: 10
