server:
  port: 8080

spring:
  application:
    name: hibiscus-signal-demo
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/hibiscus_signal_demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# Hibiscus Signal 配置
hibiscus:
  # 启用数据库持久化
  databasePersistent: true
  # 数据库表名
  databaseTableName: signal_events
  # 数据保留天数
  databaseRetentionDays: 30
  # 启用数据库清理
  enableDatabaseCleanup: true

# 日志配置
logging:
  level:
    com.hibiscus.signal: DEBUG
    org.springframework.transaction: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
